# Generated by Django 2.2.7 on 2019-11-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=20, null=True)),
                ('race_type', models.CharField(choices=[('G', 'Grayhound'), ('R', 'Racing'), ('H', 'Harness')], max_length=1)),
                ('track_condition', models.CharField(max_length=30, null=True)),
                ('weather_condition', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('href', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('direction', models.CharField(max_length=20, null=True)),
                ('has_fixed_odds', models.BooleanField(default=True)),
                ('has_parimutuel', models.BooleanField(default=True)),
                ('class_conditions', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('number_of_places', models.IntegerField(null=True)),
                ('has_results', models.BooleanField(default=False)),
                ('has_processed', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='th.Meeting')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('barrier', models.IntegerField()),
                ('trainer', models.CharField(max_length=100, null=True)),
                ('rider', models.CharField(max_length=100, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='th.Race')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_evens', models.FloatField()),
                ('quinella', models.FloatField()),
                ('exacta', models.FloatField()),
                ('duet12', models.FloatField(null=True)),
                ('duet13', models.FloatField(null=True)),
                ('duet23', models.FloatField(null=True)),
                ('trifecta', models.FloatField()),
                ('trio', models.FloatField()),
                ('first_four', models.FloatField()),
                ('running_double', models.FloatField(null=True)),
                ('early_quaddie', models.FloatField()),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='th.Runner')),
                ('fourth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='th.Runner')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='th.Race')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='th.Runner')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third', to='th.Runner')),
            ],
        ),
    ]
