# Generated by Django 2.2.7 on 2019-12-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='fixed_place',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='fixed_win',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='form_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='last_5_starts',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='tote_place',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='tote_win',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outcome',
            name='early_quaddie',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='exacta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='first_four',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='odds_evens',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='quinella',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='trifecta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='trio',
            field=models.FloatField(null=True),
        ),
    ]
