# Generated by Django 2.2.7 on 2019-12-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0002_auto_20191201_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='fixed_place',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='fixed_win',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='tote_place',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='tote_win',
            field=models.FloatField(null=True),
        ),
    ]
