# Generated by Django 2.2.7 on 2019-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0003_auto_20191201_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='quaddie',
            field=models.FloatField(null=True),
        ),
    ]
