# Generated by Django 2.2.7 on 2019-12-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0004_outcome_quaddie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='running_double',
        ),
    ]
