# Generated by Django 2.2.7 on 2019-12-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0006_auto_20191212_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='processed',
        ),
        migrations.AlterField(
            model_name='outcome',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='th.Race'),
        ),
    ]
