# Generated by Django 2.2.7 on 2019-12-12 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0007_auto_20191212_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Var',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('val1', models.FloatField(blank=True, default=0)),
                ('val2', models.FloatField(blank=True, default=0)),
                ('val3', models.FloatField(blank=True, null=True)),
                ('val4', models.FloatField(blank=True, null=True)),
                ('val5', models.FloatField(blank=True, null=True)),
                ('ran_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RunnerMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_win', models.FloatField()),
                ('fixed_place', models.FloatField()),
                ('tote_win', models.FloatField()),
                ('tote_place', models.FloatField()),
                ('won', models.BooleanField()),
                ('placed', models.BooleanField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='th.Race')),
                ('runner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='th.Runner')),
            ],
        ),
    ]
