# Generated by Django 2.0.1 on 2018-01-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='race_number',
            field=models.IntegerField(null=True),
        ),
    ]
