# Generated by Django 2.0.1 on 2018-01-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0003_auto_20180127_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('number_of_winners', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.Event')),
            ],
        ),
    ]
