# Generated by Django 2.0.1 on 2018-01-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0008_auto_20180128_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='market_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='selection_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
