# Generated by Django 2.0.1 on 2018-01-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0017_auto_20180130_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec', models.FloatField(null=True)),
                ('perc', models.FloatField(null=True)),
                ('won', models.NullBooleanField()),
                ('error', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bins', models.IntegerField()),
                ('left', models.FloatField()),
                ('right', models.FloatField()),
                ('total', models.IntegerField()),
                ('count', models.IntegerField()),
                ('win_mean', models.FloatField()),
                ('coef', models.FloatField()),
                ('intercept', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='has_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.Market'),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='runner_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.RunnerBook'),
        ),
    ]
