# Generated by Django 2.0.1 on 2018-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0030_auto_20180210_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='outcome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='profit',
            field=models.FloatField(null=True),
        ),
    ]
