BET_TYPE_WIN = 'W'
BET_TYPE_PLACE = 'P'
BET_TYPES = [BET_TYPE_WIN, BET_TYPE_PLACE]

RACE_TYPE_RACING = 'R'
RACE_TYPE_GRAYHOUND = 'G'
RACE_TYPE_HARNESS = 'H'
RACE_TYPES = [RACE_TYPE_RACING, RACE_TYPE_GRAYHOUND, RACE_TYPE_HARNESS]
