# Generated by Django 2.0.1 on 2018-01-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('QLD', 'Queensland')], max_length=10)),
                ('race_type', models.CharField(choices=[('G', 'Grayhound'), ('R', 'Racing'), ('H', 'Harness')], max_length=1)),
                ('rail_position', models.CharField(max_length=30, null=True)),
                ('track_condition', models.CharField(max_length=30)),
                ('venue_mnemonic', models.CharField(max_length=10)),
                ('weather_condition', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('link_self', models.CharField(max_length=255)),
                ('link_form', models.CharField(max_length=255)),
                ('link_big_bets', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Meeting')),
            ],
        ),
    ]
