# Generated by Django 2.0.1 on 2018-01-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_auto_20180119_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='weather_condition',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
