# Generated by Django 2.0.1 on 2018-01-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0005_auto_20180122_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='last_5_starts',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
