# Generated by Django 2.0.1 on 2018-01-22 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_auto_20180122_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Race')),
            ],
        ),
        migrations.AlterField(
            model_name='runner',
            name='link_form',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Runner'),
        ),
    ]
