# Generated by Django 2.0.1 on 2018-01-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0008_auto_20180122_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['pos']},
        ),
        migrations.AlterModelManagers(
            name='result',
            managers=[
            ],
        ),
    ]
