# Generated by Django 2.0.1 on 2018-01-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0010_auto_20180122_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedodd',
            options={'ordering': ['-as_at']},
        ),
        migrations.AlterModelOptions(
            name='parimutuelodd',
            options={'ordering': ['-as_at']},
        ),
        migrations.AlterField(
            model_name='runner',
            name='trainer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
