# Generated by Django 2.0.1 on 2018-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_auto_20180123_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='dfs_form_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='fixed_betting_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='parimutuel_betting_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='tech_form_rating',
            field=models.IntegerField(null=True),
        ),
    ]
