# Generated by Django 2.0.1 on 2018-01-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0016_auto_20180126_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('mean', models.FloatField()),
                ('std', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
