# Generated by Django 2.0.1 on 2018-01-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0019_auto_20180126_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='start',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='bucket',
            old_name='end',
            new_name='right',
        ),
    ]
