# Generated by Django 2.0.1 on 2018-01-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0020_auto_20180126_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='error_mean',
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='error_std',
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='win_std',
        ),
        migrations.AddField(
            model_name='bucket',
            name='coef_a',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucket',
            name='coef_b',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
