# Generated by Django 2.0.1 on 2018-01-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0021_auto_20180126_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='coef_a',
            new_name='coef',
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='coef_b',
        ),
        migrations.AddField(
            model_name='bucket',
            name='intercept',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
