# Generated by Django 2.0.1 on 2018-01-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0003_auto_20180127_1845'),
        ('tab', '0022_auto_20180126_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='betfair_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betfair.Event'),
        ),
    ]
