# Generated by Django 2.0.1 on 2018-01-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0024_auto_20180128_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='win_market',
        ),
    ]
