# Generated by Django 2.0.1 on 2018-01-28 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0004_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_delay', models.FloatField()),
                ('bsp_reconciled', models.BooleanField()),
                ('complete', models.BooleanField()),
                ('cross_matching', models.BooleanField()),
                ('inplay', models.BooleanField()),
                ('is_market_data_delayed', models.BooleanField()),
                ('last_match_time', models.DateTimeField()),
                ('number_of_active_runners', models.IntegerField()),
                ('number_of_runners', models.IntegerField()),
                ('number_of_winners', models.IntegerField()),
                ('runners_voidable', models.BooleanField()),
                ('status', models.CharField(max_length=50)),
                ('total_available', models.FloatField()),
                ('total_matched', models.FloatField()),
                ('version', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sort_priority', models.IntegerField()),
                ('handicap', models.FloatField()),
                ('cloth_number', models.IntegerField()),
                ('stall_draw', models.IntegerField()),
                ('runner_id', models.BigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='open_date',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='type',
            new_name='market_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='race_number',
        ),
        migrations.RemoveField(
            model_name='market',
            name='number_of_winners',
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='betting_type',
            field=models.CharField(default='ODDS', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='market_time',
            field=models.DateTimeField(default='2018-01-28T00:50:00.000Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='name',
            field=models.CharField(default='market', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='race_type',
            field=models.CharField(default='Harness', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='suspend_time',
            field=models.DateTimeField(default='2018-01-28T00:50:00.000Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='total_matched',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='turn_in_play_enabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.Market'),
        ),
        migrations.AddField(
            model_name='book',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.Market'),
        ),
    ]
