# Generated by Django 2.0.1 on 2018-01-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0006_auto_20180128_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='cloth_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='stall_draw',
            field=models.IntegerField(null=True),
        ),
    ]
