# Generated by Django 2.0.1 on 2018-01-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0011_auto_20180128_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerbook',
            name='adjustment_factor',
            field=models.FloatField(null=True),
        ),
    ]
