# Generated by Django 2.0.1 on 2018-01-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0014_auto_20180128_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_matched',
            field=models.FloatField(null=True),
        ),
    ]
