# Generated by Django 2.0.1 on 2018-02-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0022_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='margin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
