# Generated by Django 2.0.1 on 2018-02-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0024_auto_20180204_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='liability',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='matched_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='payout',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='size_cancelled',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='size_lapsed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='size_matched',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='size_voided',
            field=models.FloatField(default=0),
        ),
    ]
