# Generated by Django 2.0.1 on 2018-01-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('country_code', models.CharField(max_length=10)),
                ('race_number', models.IntegerField()),
            ],
        ),
    ]
