# Generated by Django 2.0.1 on 2018-01-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0005_auto_20180128_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='race_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
