# Generated by Django 2.0.1 on 2018-01-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0007_auto_20180128_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('adjustment_factor', models.FloatField()),
                ('last_price_traded', models.FloatField(null=True)),
                ('total_matched', models.FloatField()),
                ('back_price', models.FloatField(null=True)),
                ('back_size', models.FloatField(null=True)),
                ('lay_price', models.FloatField(null=True)),
                ('lay_size', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['version']},
        ),
        migrations.AddField(
            model_name='runnerbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.Book'),
        ),
        migrations.AddField(
            model_name='runnerbook',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='betfair.Runner'),
        ),
    ]
