# Generated by Django 2.0.1 on 2018-01-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0010_auto_20180128_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
