# Generated by Django 2.0.1 on 2018-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0012_auto_20180128_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerbook',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
