# Generated by Django 2.0.1 on 2018-01-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0019_market_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betfair.Market'),
        ),
    ]
