# Generated by Django 2.0.1 on 2018-02-04 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0023_bet_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='placed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
