# Generated by Django 2.0.1 on 2018-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0027_remove_market_bets_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='matched_at',
        ),
        migrations.AddField(
            model_name='bet',
            name='persistence_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
