# Generated by Django 2.0.1 on 2018-02-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0029_auto_20180210_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='size_remaining',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='size_cancelled',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='size_lapsed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='size_matched',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='size_voided',
            field=models.FloatField(null=True),
        ),
    ]
