# Generated by Django 2.0.1 on 2018-02-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0032_bet_bracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='trade',
            field=models.FloatField(null=True),
        ),
    ]
