import logging

import requests
from celery import shared_task
from channels import Group
from django.core.cache import cache

from .models import Meeting

logger = logging.getLogger(__name__)


@shared_task
def scrape_races():
    """Scrapes the Next-To-Go races from TAB"""
    url = 'https://api.beta.tab.com.au/v1/tab-info-service/racing/next-to-go/races?jurisdiction=NSW'
    res = requests.get(url)
    res.raise_for_status()
    res = res.json()
    logger.info('Scraped {} races'.format(len(res['races'])))
    for item in res['races']:
        race, created = upsert_race(item)
        if created:
            logger.info('Created {}'.format(race))
        if not cache.get(race.pk):
            cache.set(race.pk, 1)
            monitor_race.delay(race.pk)
            logger.info('Monitoring {}'.format(race))
        else:
            logger.debug('Already monitoring {}'.format(race))


@shared_task
def monitor_race(pk):
    """Monitor the race"""
    logger.info('Monitoring race id {}'.format(pk))


@shared_task
def upsert_race(item):
    meeting, created = upsert_meeting(item['meeting'])
    if created:
        logger.info('Created {}'.format(meeting))
    try:
        return meeting.race_set.update_or_create(
            number=item['raceNumber'],
            defaults={
                'distance': item['raceDistance'],
                'name': item['raceName'].capitalize(),
                'start_time': item['raceStartTime'],
                'link_self': item['_links']['self'],
                'link_form': item['_links']['form'],
                'link_big_bets': item['_links']['bigBets'],
            }
        )
    except:
        logger.warning(item)
        raise


@shared_task
def upsert_meeting(item):
    """Upsert a meeting into the db"""
    try:
        return Meeting.objects.update_or_create(
            name=item['meetingName'].capitalize(),
            date=item['meetingDate'],
            defaults={
                'location': item['location'],
                'race_type': item['raceType'],
                'rail_position': item['railPosition'],
                'track_condition': item['trackCondition'],
                'venue_mnemonic': item['venueMnemonic'],
                'weather_condition': item['weatherCondition'],
            }
        )
    except:
        logger.warning(item)
        raise


'''
{'races':
    [
        {
            '_links': {
                'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/IPS/races/10/big-bets?jurisdiction=NSW',
                'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/IPS/races/10/form?jurisdiction=NSW',
                'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/IPS/races/10?jurisdiction=NSW'
            },
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {
                'location': 'QLD',
                'meetingDate': '2018-01-19',
                'meetingName': 'IPSWICH',
                'raceType': 'G',
                'railPosition': None,
                'sellCode': {'meetingCode': 'B', 'scheduledType': 'G'},
                'trackCondition': 'GOOD',
                'venueMnemonic': 'IPS',
                'weatherCondition': 'FINE'},
            'raceDistance': 431,
            'raceName': 'WWW.IPSWICHGREYHOUNDS.COM',
            'raceNumber': 10,
            'raceStartTime': '2018-01-19T07:42:00.000Z'
        },
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/AXP/races/6/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/AXP/races/6/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/AXP/races/6?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'NZL',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'ALEXANDRA PARK',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'Y', 'scheduledType': 'H'},
                        'trackCondition': 'FAST',
                        'venueMnemonic': 'AXP',
                        'weatherCondition': 'FINE'},
            'raceDistance': 2200,
            'raceName': 'DON GLASGOW MEMORIAL PACE MS',
            'raceNumber': 6,
            'raceStartTime': '2018-01-19T07:44:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CBY/races/2/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CBY/races/2/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CBY/races/2?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'CANTERBURY',
                        'raceType': 'R',
                        'railPosition': '+3m Entire Circuit',
                        'sellCode': {'meetingCode': 'S', 'scheduledType': 'R'},
                        'trackCondition': 'GOOD4',
                        'venueMnemonic': 'CBY',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1100,
            'raceName': 'TAB HANDICAP',
            'raceNumber': 2,
            'raceStartTime': '2018-01-19T07:45:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HOB/races/12/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HOB/races/12/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HOB/races/12?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'TAS',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'HOBART',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'E', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'HOB',
                        'weatherCondition': 'FINE'},
            'raceDistance': 461,
            'raceName': 'SKY RACING MAIDEN THOUSAND HEAT',
            'raceNumber': 12,
            'raceStartTime': '2018-01-19T07:49:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/1/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/1/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/1?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'VIC',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'MELTON',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'M', 'scheduledType': 'H'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'MLT',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1720,
            'raceName': 'DNR LOGISTICS PACE MS',
            'raceNumber': 1,
            'raceStartTime': '2018-01-19T07:52:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HAT/races/10/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HAT/races/10/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HAT/races/10?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'NZL',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'HATRICK',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'Y', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'HAT',
                        'weatherCondition': 'OCAST'},
            'raceDistance': 305,
            'raceName': 'NZ RACING SERIES SPRINT HT 4 C0-C5',
            'raceNumber': 10,
            'raceStartTime': '2018-01-19T07:55:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/GOS/races/10/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/GOS/races/10/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/GOS/races/10?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'GOSFORD',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'C', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'GOS',
                        'weatherCondition': 'FINE'},
            'raceDistance': 400,
            'raceName': 'DAVID MEEHAN MP STAKES',
            'raceNumber': 10,
            'raceStartTime': '2018-01-19T07:57:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CRB/races/2/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CRB/races/2/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CRB/races/2?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'VIC',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'CRANBOURNE',
                        'raceType': 'R',
                        'railPosition': 'Out 6m Entire Circuit',
                        'sellCode': {'meetingCode': 'M', 'scheduledType': 'R'},
                        'trackCondition': 'GOOD4',
                        'venueMnemonic': 'CRB',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1300,
            'raceName': 'PROCON DEVELOPMENTS MAIDEN PLATE',
            'raceNumber': 2,
            'raceStartTime': '2018-01-19T08:00:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/BGM/races/9/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/BGM/races/9/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/BGM/races/9?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'KOR',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'BUSAN KOREA',
                        'raceType': 'R',
                        'railPosition': 'True',
                        'sellCode': {'meetingCode': 'T', 'scheduledType': 'R'},
                        'trackCondition': 'AWT',
                        'venueMnemonic': 'BGM',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1000,
            'raceName': 'BUSAN CLASS 4 HANDICAP',
            'raceNumber': 9,
            'raceStartTime': '2018-01-19T08:00:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/BAT/races/1/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/BAT/races/1/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/BAT/races/1?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'BATHURST',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'S', 'scheduledType': 'H'},
                        'trackCondition': 'FAST',
                        'venueMnemonic': 'BAT',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1730,
            'raceName': 'OBERON COUNCIL PACE MS',
            'raceNumber': 1,
            'raceStartTime': '2018-01-19T08:03:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/ESP/races/6/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/ESP/races/6/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/ESP/races/6?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'WA',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'ESPERANCE',
                        'raceType': 'R',
                        'railPosition': 'Out 4 metres. CUTAWAY IN STRAIGHT',
                        'sellCode': {'meetingCode': 'W', 'scheduledType': 'R'},
                        'trackCondition': 'GOOD3',
                        'venueMnemonic': 'ESP',
                        'weatherCondition': 'OCAST'},
            'raceDistance': 1200,
            'raceName': 'FREIGHT LINES GROUP HANDICAP',
            'raceNumber': 6,
            'raceStartTime': '2018-01-19T08:08:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/AXP/races/7/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/AXP/races/7/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/AXP/races/7?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'NZL',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'ALEXANDRA PARK',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'Y', 'scheduledType': 'H'},
                        'trackCondition': 'FAST',
                        'venueMnemonic': 'AXP',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1700,
            'raceName': 'CHINESE NEW YEAR 9 FEB MS',
            'raceNumber': 7,
            'raceStartTime': '2018-01-19T08:10:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CBY/races/3/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CBY/races/3/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CBY/races/3?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'CANTERBURY',
                        'raceType': 'R',
                        'railPosition': '+3m Entire Circuit',
                        'sellCode': {'meetingCode': 'S', 'scheduledType': 'R'},
                        'trackCondition': 'GOOD4',
                        'venueMnemonic': 'CBY',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1900,
            'raceName': '#THERACES HANDICAP',
            'raceNumber': 3,
            'raceStartTime': '2018-01-19T08:15:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/GOS/races/11/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/GOS/races/11/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/GOS/races/11?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'GOSFORD',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'C', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'GOS',
                        'weatherCondition': 'FINE'},
            'raceDistance': 400,
            'raceName': 'GOSFORD NIGHT MARKET TUES STKS',
            'raceNumber': 11,
            'raceStartTime': '2018-01-19T08:18:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/2/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/2/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/2?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'VIC',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'MELTON',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'M', 'scheduledType': 'H'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'MLT',
                        'weatherCondition': 'FINE'},
            'raceDistance': 2240,
            'raceName': 'SUMMER OF GLORY 2018 PACE FINAL MS',
            'raceNumber': 2,
            'raceStartTime': '2018-01-19T08:20:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HAT/races/11/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HAT/races/11/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HAT/races/11?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'NZL',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'HATRICK',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'Y', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'HAT',
                        'weatherCondition': 'OCAST'},
            'raceDistance': 305,
            'raceName': 'NZ RACING SERIES SPRINT HT 5 C0-C5',
            'raceNumber': 11,
            'raceStartTime': '2018-01-19T08:21:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MTG/races/1/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MTG/races/1/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MTG/races/1?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'SA',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'MOUNT GAMBIER',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'A', 'scheduledType': 'H'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'MTG',
                        'weatherCondition': 'FINE'},
            'raceDistance': 2190,
            'raceName': 'BENDIGO BANK PACE MS',
            'raceNumber': 1,
            'raceStartTime': '2018-01-19T08:25:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CRB/races/3/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CRB/races/3/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CRB/races/3?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'VIC',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'CRANBOURNE',
                        'raceType': 'R',
                        'railPosition': 'Out 6m Entire Circuit',
                        'sellCode': {'meetingCode': 'M', 'scheduledType': 'R'},
                        'trackCondition': 'GOOD4',
                        'venueMnemonic': 'CRB',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1400,
            'raceName': 'R & C ASPHALT 3YO FILLIES MAIDEN',
            'raceNumber': 3,
            'raceStartTime': '2018-01-19T08:30:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/BGM/races/10/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/BGM/races/10/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/BGM/races/10?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'KOR',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'BUSAN KOREA',
                        'raceType': 'R',
                        'railPosition': 'True',
                        'sellCode': {'meetingCode': 'T', 'scheduledType': 'R'},
                        'trackCondition': 'AWT',
                        'venueMnemonic': 'BGM',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1200,
            'raceName': 'BUSAN CLASS 3 HANDICAP',
            'raceNumber': 10,
            'raceStartTime': '2018-01-19T08:30:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/BAT/races/2/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/BAT/races/2/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/BAT/races/2?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'BATHURST',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'S', 'scheduledType': 'H'},
                        'trackCondition': 'FAST',
                        'venueMnemonic': 'BAT',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1730,
            'raceName': 'BOWYER & LIVERMORE 3YO PACE MS',
            'raceNumber': 2,
            'raceStartTime': '2018-01-19T08:33:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/ESP/races/7/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/ESP/races/7/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/ESP/races/7?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'WA',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'ESPERANCE',
                        'raceType': 'R',
                        'railPosition': 'Out 4 metres. CUTAWAY IN STRAIGHT',
                        'sellCode': {'meetingCode': 'W', 'scheduledType': 'R'},
                        'trackCondition': 'GOOD3',
                        'venueMnemonic': 'ESP',
                        'weatherCondition': 'OCAST'},
            'raceDistance': 1100,
            'raceName': 'ESPERANCE AGISTMENT CENTRE',
            'raceNumber': 7,
            'raceStartTime': '2018-01-19T08:38:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/AXP/races/8/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/AXP/races/8/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/AXP/races/8?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'NZL',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'ALEXANDRA PARK',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'Y', 'scheduledType': 'H'},
                        'trackCondition': 'FAST',
                        'venueMnemonic': 'AXP',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1700,
            'raceName': 'CROMBIE LOCKWOOD BLOODSTOCK MS',
            'raceNumber': 8,
            'raceStartTime': '2018-01-19T08:40:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/RIC/races/1/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/RIC/races/1/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/RIC/races/1?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'RICHMOND',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'S', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'RIC',
                        'weatherCondition': 'FINE'},
            'raceDistance': 400,
            'raceName': 'LADBROKES MULTIMAKER MAIDEN',
            'raceNumber': 1,
            'raceStartTime': '2018-01-19T08:42:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CBY/races/4/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CBY/races/4/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CBY/races/4?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'CANTERBURY',
                        'raceType': 'R',
                        'railPosition': '+3m Entire Circuit',
                        'sellCode': {'meetingCode': 'S', 'scheduledType': 'R'},
                        'trackCondition': 'GOOD4',
                        'venueMnemonic': 'CBY',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1250,
            'raceName': 'TAB.COM.AU HANDICAP',
            'raceNumber': 4,
            'raceStartTime': '2018-01-19T08:45:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/WAG/races/1/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/WAG/races/1/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/WAG/races/1?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'WAGGA',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'J', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'WAG',
                        'weatherCondition': 'FINE'},
            'raceDistance': 320,
            'raceName': 'WAGGA TILE CENTRE MAIDEN',
            'raceNumber': 1,
            'raceStartTime': '2018-01-19T08:45:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/GEL/races/1/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/GEL/races/1/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/GEL/races/1?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'VIC',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'GEELONG',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'M', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'GEL',
                        'weatherCondition': 'FINE'},
            'raceDistance': 460,
            'raceName': 'BECKLEY CENTRE CLUB FUNDRAISING',
            'raceNumber': 1,
            'raceStartTime': '2018-01-19T08:48:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/3/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/3/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/3?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'VIC',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'MELTON',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'M', 'scheduledType': 'H'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'MLT',
                        'weatherCondition': 'FINE'},
            'raceDistance': 2240,
            'raceName': 'TAB MULTIPLIER PACE FINAL MS',
            'raceNumber': 3,
            'raceStartTime': '2018-01-19T08:50:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HAT/races/12/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HAT/races/12/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/HAT/races/12?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'NZL',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'HATRICK',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'Y', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'HAT',
                        'weatherCondition': 'OCAST'},
            'raceDistance': 305,
            'raceName': 'NZ RACING SERIES SPRINT HT 6 C0-C5',
            'raceNumber': 12,
            'raceStartTime': '2018-01-19T08:51:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MTG/races/2/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MTG/races/2/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MTG/races/2?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'SA',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'MOUNT GAMBIER',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'A', 'scheduledType': 'H'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'MTG',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1385,
            'raceName': 'GEAR SUPPLIES SPRINT ROUND 1 MS',
            'raceNumber': 2,
            'raceStartTime': '2018-01-19T08:54:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/RIC/races/2/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/RIC/races/2/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/RIC/races/2?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'RICHMOND',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'S', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'RIC',
                        'weatherCondition': 'FINE'},
            'raceDistance': 535,
            'raceName': 'LADBROKES ODDS BOOST MAIDEN FINAL',
            'raceNumber': 2,
            'raceStartTime': '2018-01-19T08:58:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CRB/races/4/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CRB/races/4/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/CRB/races/4?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'VIC',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'CRANBOURNE',
                        'raceType': 'R',
                        'railPosition': 'Out 6m Entire Circuit',
                        'sellCode': {'meetingCode': 'M', 'scheduledType': 'R'},
                        'trackCondition': 'GOOD4',
                        'venueMnemonic': 'CRB',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1000,
            'raceName': 'MYPUNTER.COM F&M MAIDEN PLATE',
            'raceNumber': 4,
            'raceStartTime': '2018-01-19T09:00:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/BGM/races/11/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/BGM/races/11/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/BGM/races/11?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'KOR',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'BUSAN KOREA',
                        'raceType': 'R',
                        'railPosition': 'True',
                        'sellCode': {'meetingCode': 'T', 'scheduledType': 'R'},
                        'trackCondition': 'AWT',
                        'venueMnemonic': 'BGM',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1200,
            'raceName': 'BUSAN CLASS 2 HANDICAP',
            'raceNumber': 11,
            'raceStartTime': '2018-01-19T09:00:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/BAT/races/3/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/BAT/races/3/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/BAT/races/3?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'BATHURST',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'S', 'scheduledType': 'H'},
                        'trackCondition': 'FAST',
                        'venueMnemonic': 'BAT',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1730,
            'raceName': 'JENOLAN CARAVAN PARK PACE MS',
            'raceNumber': 3,
            'raceStartTime': '2018-01-19T09:03:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/WAG/races/2/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/WAG/races/2/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/G/WAG/races/2?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 2',
            'broadcastChannels': ['Sky Racing 2'],
            'meeting': {'location': 'NSW',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'WAGGA',
                        'raceType': 'G',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'J', 'scheduledType': 'G'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'WAG',
                        'weatherCondition': 'FINE'},
            'raceDistance': 320,
            'raceName': 'HAPPY BDAY BILLY MCGOVERN MDN',
            'raceNumber': 2,
            'raceStartTime': '2018-01-19T09:07:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/ESP/races/8/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/ESP/races/8/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/R/ESP/races/8?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'WA',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'ESPERANCE',
                        'raceType': 'R',
                        'railPosition': 'Out 4 metres. CUTAWAY IN STRAIGHT',
                        'sellCode': {'meetingCode': 'W', 'scheduledType': 'R'},
                        'trackCondition': 'GOOD3',
                        'venueMnemonic': 'ESP',
                        'weatherCondition': 'OCAST'},
            'raceDistance': 2000,
            'raceName': 'C.C. SPROULE HANDICAP',
            'raceNumber': 8,
            'raceStartTime': '2018-01-19T09:08:00.000Z'},
        {'_links': {
            'bigBets': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/4/big-bets?jurisdiction=NSW',
            'form': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/4/form?jurisdiction=NSW',
            'self': 'https://api.beta.tab.com.au/v1/tab-info-service/racing/dates/2018-01-19/meetings/H/MLT/races/4?jurisdiction=NSW'},
            'broadcastChannel': 'Sky Racing 1',
            'broadcastChannels': ['Sky Racing 1'],
            'meeting': {'location': 'VIC',
                        'meetingDate': '2018-01-19',
                        'meetingName': 'MELTON',
                        'raceType': 'H',
                        'railPosition': None,
                        'sellCode': {'meetingCode': 'M', 'scheduledType': 'H'},
                        'trackCondition': 'GOOD',
                        'venueMnemonic': 'MLT',
                        'weatherCondition': 'FINE'},
            'raceDistance': 1720,
            'raceName': 'NEVELE R STUD CLAIMING PACE MS',
            'raceNumber': 4,
            'raceStartTime': '2018-01-19T09:20:00.000Z'}]}
'''
