# Generated by Django 2.0.1 on 2018-01-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='track_condition',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
