# Generated by Django 2.0.1 on 2018-01-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0014_auto_20180126_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuracy',
            name='place',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='place_dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='place_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='tab_place_error',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='tab_win_error',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='win_dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='win_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='won',
            field=models.NullBooleanField(),
        ),
    ]
