# Generated by Django 2.0.1 on 2018-01-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0007_auto_20180128_1339'),
        ('tab', '0023_race_betfair_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='betfair_event',
        ),
        migrations.AddField(
            model_name='race',
            name='win_market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betfair.Market'),
        ),
    ]
