# Generated by Django 2.2.7 on 2019-11-10 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0027_auto_20180131_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_odds', models.FloatField()),
                ('place_odds', models.FloatField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='accuracy',
            name='race',
        ),
        migrations.RemoveField(
            model_name='accuracy',
            name='runner',
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='runner',
            options={'ordering': ['barrier_number', 'runner_number']},
        ),
        migrations.DeleteModel(
            name='Accuracy',
        ),
        migrations.AddField(
            model_name='runnermeta',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Race'),
        ),
        migrations.AddField(
            model_name='runnermeta',
            name='runner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tab.Runner'),
        ),
    ]
