# Generated by Django 2.2.7 on 2019-11-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0029_auto_20191110_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Var',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('val1', models.FloatField()),
                ('val2', models.FloatField(null=True)),
                ('val3', models.FloatField(null=True)),
                ('val4', models.FloatField(null=True)),
                ('val5', models.FloatField(null=True)),
            ],
        ),
    ]
