# Generated by Django 2.2.7 on 2019-11-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0030_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='val1',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='var',
            name='val2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='var',
            name='val3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='var',
            name='val4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='var',
            name='val5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
