# Generated by Django 2.2.7 on 2019-11-10 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0031_auto_20191111_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='ran_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
