# Generated by Django 2.0.1 on 2018-01-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0004_auto_20180122_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='rider_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
