# Generated by Django 2.0.1 on 2018-01-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0009_auto_20180122_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='fixed_odds_update_time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='odds_update_time',
        ),
    ]
