# Generated by Django 2.0.1 on 2018-01-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0015_auto_20180126_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accuracy',
            old_name='tab_place_error',
            new_name='place_error',
        ),
        migrations.RenameField(
            model_name='accuracy',
            old_name='tab_win_error',
            new_name='win_error',
        ),
    ]
