# Generated by Django 2.0.1 on 2018-01-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0017_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='bins',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
