# Generated by Django 2.0.1 on 2018-01-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0025_remove_race_win_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='link_form',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
