# Generated by Django 2.0.1 on 2018-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0026_auto_20180131_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parimutuelodd',
            name='place_dec',
            field=models.FloatField(null=True),
        ),
    ]
